language: go

sudo: false

# as we don't use travis to actually deploy the blog, there is no need to init the submodules (travel photos)
git:
    submodules: false

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.tar.gz
    - tar xzf hugo_0.54.0_Linux-64bit.tar.gz

script: "./hugo"
