highlighter: rouge
markdown: kramdown
timezone: Europe/Paris
encoding: utf-8
exclude: [ README.md, Gemfile ]
permalink: pretty

globals:
    author: Kévin Gomez
    title: Kévin Gomez
    url: 'http://blog.kevingomez.fr'
    email: contact@kevingomez.fr

    menu:
        - url: /bookshelf/
          title: Bookshelf
        - url: /talks/
          title: Talks
        - url: /about-me/
          title: About me
