highlighter: pygments
markdown: redcarpet
timezone: Europe/Paris
encoding: utf-8
exclude: [ README.md, Gemfile ]
permalink: pretty

config:
    author: Kévin Gomez
    title:  Kévin Gomez
    url:    http://blog.kevingomez.fr
    email:  contact@kevingomez.fr

    menu:
        - url:    http://www.kevingomez.fr
          title:  about
        - url:    /bookshelf/
          title:  bookshelf
