highlighter: pygments
markdown: redcarpet
timezone: Europe/Paris
encoding: utf-8
exclude: [ README.md, Gemfile ]
permalink: pretty

site:
    author: Kévin Gomez
    title:  Kévin Gomez
    url:    http://blog.kevingomez.fr
    email:  contact@kevingomez.fr
