title = "Kévin Gomez"
baseurl = "/"
languageCode = "en-us"

pygmentsCodeFences = true
enableGitInfo = true

[params]
    author = "Kévin Gomez"
    mainSections = ["posts", "til"]

[frontmatter]
    lastmod = ["lastmod"]
    date = ["date", ":filename", "lastmod"]
    publishDate = ["publishDate", "date"]

[permalinks]
    posts = "/:year/:month/:day/:title/"
