title = "Kévin Gomez"
baseurl = "https://blog.kevingomez.fr"
languageCode = "en-us"

theme = "PaperMod"

enableGitInfo = false
disableHugoGeneratorInject = true
disableKinds = ["sitemap"]

[minify]
  minifyOutput = false # TODO: enable

[params]
  env = "production" # to enable google analytics, opengraph, twitter-cards and schema.

  author = "Kévin Gomez"
  mainSections = ["posts", "til"]

  ShowReadingTime = true
  ShowToc = true
  ShowCodeCopyButtons = true
  ShowFullTextinRSS = true
  ShowRssButtonInSectionTermList = true
  disableScrollToTop = true
  disableSpecial1stPost = true

  [params.assets]
  disableHLJS = true

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/K-Phoen"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/kevingomez/"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://hachyderm.io/@kphoen"

[menu]
  [[menu.main]]
  identifier = 'bookshelf'
  name = 'Bookshelf'
  url = '/bookshelf/'
  weight = 10
  [[menu.main]]
  identifier = "talks"
  name = "Talks"
  url = "/talks/"
  weight = 20
  [[menu.main]]
  identifier = "about-me"
  name = "About me"
  url = "/about-me/"
  weight = 30

[social]
  twitter = "KPhoen"

[frontmatter]
  lastmod = ["lastmod"]
  date = ["date", "lastmod", ":git"]
  publishDate = ["publishDate", "date"]

[permalinks]
  [permalinks.page]
    posts = "/:year/:month/:day/:slug/"

[markup]
  [markup.goldmark.renderer]
    unsafe= true

  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
    guessSyntax = true
    style = 'onedark'
    tabWidth = 2
    noClasses = false

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
