title = "Kévin Gomez"
baseurl = "/"
languageCode = "en-us"

enableGitInfo = false
disableHugoGeneratorInject = true
disableKinds = ["sitemap"]

[params]
    author = "Kévin Gomez"
    mainSections = ["posts", "til"]

[social]
    twitter = "KPhoen"

[frontmatter]
    lastmod = ["lastmod"]
    date = ["date", ":contentbasename", "lastmod", ":git"]
    publishDate = ["publishDate", "date"]

[permalinks]
    posts = "/:year/:month/:day/:contentbasename/"

[markup]
  [markup.goldmark.renderer]
    unsafe= true

  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    style = 'onedark'
    tabWidth = 4
