name: CI
on: [pull_request]

jobs:
  markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          depth: 1

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@master
        with:
          files: ./content/
