name: CI
on: [pull_request]

jobs:
  markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          depth: 1

      - uses: nosborn/github-action-markdown-cli@master
        with:
          files: ./content/

  language:
    name: Language
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          depth: 1

      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ github.token }}
          locale: "US"

      - name: alexjs
        uses: theashraf/alex-action@master

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          depth: 1

      - uses: peaceiris/actions-hugo@v2.3.0
        with:
          hugo-version: '0.59.1'

      - run: hugo
