name: CI
on: [pull_request]

jobs:
  markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: nosborn/github-action-markdown-cli@v3.0.0
        with:
          files: ./content/
          config_file: .markdownlint.json

  language:
    name: Language
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          depth: 1

      - uses: K-Phoen/action-misspell@master
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          locale: "US"

      - name: alexjs
        uses: theashraf/alex-action@master

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          depth: 1

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.59.1'

      - run: hugo
