name: Deploy
on:
  push:
    branches: [master]

jobs:
  hugo_deploy:
    name: Hugo
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, 'Automatic deployment')"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive
          token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}

      - uses: K-Phoen/hugo-gh-pages-action@master
        with:
          github_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
          hugo_version: '0.111.2'
