name: Deploy
on:
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    name: Publish Docker image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_VERSION=${GITHUB_SHA::6} make build
          IMAGE_VERSION=${GITHUB_SHA::6} make push

      - name: Deploy to Kubernetes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global url."https://x-access-token:${{ secrets.DEPLOY_PAT }}@github.com/".insteadOf "git@github.com:"

          ./scripts/deploy.sh "${GITHUB_SHA::6}"
        env:
          TERM: 'xterm'
          LOG_LEVEL: '7' # debug
          DRY_RUN: 'no'

